config/routes.rb
Rails.application.routes.draw do
 resources :pages, param: :slug
 get 'pages/:slug' => 'pages#show'
 root :to => 'pages#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/page.rb
class Page < ApplicationRecord
before_create :create_slug
  validates :slug, uniqueness: true, presence: true, length: {maximum:30}  

  def to_param
    "#{slug}".downcase 
  end

  def create_slug
    self.slug=self.slug.parameterize
  end
                               
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def index
    @check = false
    @titletext = "Test Blog, Test Title. CRUD With Addons."
    @metadescription = "Page contained a list of created page."
     @pages = Page.all.order("priority")
     @pagesN = Page.where(params[:page]).order("priority")
     @pagesN.each do |page|
      if page.published == false
        @check = true
        end
     end 
  end

  def new
    @titletext = "Create new page - Test Blog"
    @metadescription = "Create new page with many parameters"
    @pages = Page.all
    @page = Page.new
  end

  def edit
    @page = Page.where(:slug => params[:slug]).first
    @pages = Page.all
    @titletext = @page.title + " (Title Area) - Edit Page"
    @metadescription = "Page editor with many parameters"
  end

  def create
     @titletext = "Create new page - Test Blog"
    @metadescription = "Create new page with many parameters"
    @pages = Page.all
    @page = Page.new(page_params)
      if @page.save
         redirect_to @page
      else 
    render 'new'
  end
  end
  
 def update
  @pages = Page.all
    @page = Page.where(:slug => params[:slug]).first
      @titletext = @page.title + " (Title Area) - Edit Page"
    @metadescription = "Page editor with many parameters"
      if @page.update(page_params)
         redirect_to @page
      else
      render 'edit'
    end
end

  def destroy
    @page = Page.where(:slug => params[:slug]).first
    @page.destroy
    redirect_to pages_path
  end

  def show
    @pages = Page.all
    @page = Page.where(:slug => params[:slug]).first
    @titletext = @page.title + " (Title Area) - READ PAGE MODE"
    @metadescription = @page.description
    @choosedPage = @page.slug
  end
     
  private
  def page_params
    params.require(:page).permit(:title, :description, :slug,:published, :menu_label, :h1, :content, :published_at, :priority)
  end

end 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%=@titletext%></title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="<%=@metadescription%>">
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>

  
  <nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false"> 
      </button>
      <a class="navbar-brand" href="/">Index Page</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">

    <%  @pages.each do |pagesc|%>
      <%  if pagesc.published == true%>
        <% if @choosedPage == pagesc.slug%>
        <li class="active"><a href="<%="http://"+request.host_with_port + "/pages/" + pagesc.slug %>"><%= pagesc.menu_label %></a></li>
        <%else%>
        <li><a href="<%="http://"+request.host_with_port + "/pages/" + pagesc.slug %>"><%= pagesc.menu_label %></a></li>
        <%end%>
       <% end%>
    <%end %>
      </ul>
      
      
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav><div class="container">
    <%= yield %>
    </div>
    <footer class="footer">
      <div class="container">
        <p class="text-muted">Andrew PyramidMello Prosencov, 2016</p>
      </div>
    </footer>
  </body>
</html>

app/views/pages/_form.html.erb
<%= form_for(page) do |f| %>
  <% if page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(page.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
      <% page.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<script>
      $(function() {
          $('#page_content').froalaEditor({
      heightMin: 200,
      heightMax: 500
    })
      });
  </script>
  
<div class="container-fluid">
  <div class="row">
    <div class="col-md-12">
    <div class="row">
    <div class="col-md-4">
    <div class="actions">
    <%= f.submit %>
  </div>
      <div class="field">
    <%= f.label "Publish" %>
    <%= f.check_box :published %><br>
  </div>
  <div class="field">
    <%= f.label "Date And Time:" %><br>
    <%= f.datetime_select :published_at %><br>
  </div>
    </div>
   </div>
    </div>
    <div class="col-md-12">
      <div class="row">
        <div class="col-md-4">
         
            <div class="field">
            <%= f.label :slug %><br>
             <%= f.text_field :slug %><br>
          </div>
          
        </div>
        <div class="col-md-4">
         
            <div class="field">
    <%= f.label :menu_label %><br>
    <%= f.text_field :menu_label %><br>
  </div>
          
        </div>
        <div class="col-md-4">
         
            <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field:title %><br>
  </div>
          
        </div>
      </div>
      <div class="row">
        <div class="col-md-4">
          
              <div class="field">
    <%= f.label :priority %><br>
    <%= f.number_field :priority %><br>
  </div>
          
        </div>
        <div class="col-md-4">
        
           <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %><br>
  </div>
         
        </div>
        <div class="col-md-4">
         
             <div class="field">
    <%= f.label :h1 %><br>
    <%= f.text_area :h1 %><br>
  </div>
          
        </div>
      </div>
      <div class="row">
        <div class="col-md-4">
         
        </div>
        <div class="col-md-4">
         
        </div>
        <div class="col-md-4">
         </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          
            <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %><br>
  </div>
        
        </div>
      </div>
    </div>
  </div>
</div> 
<% end %>

app/views/pages/edit.html.erb
<h1>Editing Page: <%= @page.menu_label %>
 </h1> 
<%= render 'form', page: @page %>
<br>
<%= link_to raw('<i class="fa fa-sticky-note-o" aria-hidden="true"></i> Show'), @page %> |
<%= link_to raw('<i class="fa fa-level-up" aria-hidden="true"></i> Back'), pages_path %>

app/views/pages/index.html.erb
<% if @check == true%>
<div class="alert alert-block">
  <a class="close" data-dismiss="alert" href="#">×</a>
  <h4 class="alert-heading">You have unpublished page(s)!</h4>
  <button class="btn " data-toggle="collapse" data-target="#hide-me">Open</button>
</div>
<%end%>

<% if @check == true %>

<div id="hide-me" class="collapse out">
<table class="table table-bordered table-striped">
<thead>
    <tr>
      <th>Slug</th>
      <th>Menu label</th>
      <th>Published at</th>
      <th>Published</th>
      <th>Priority</th>
      <th>Title</th>
      <th>Description</th>
      <th>H1</th>
      <th>Content(HTML TAGS OFF)</th>
      <th colspan="3"></th>
    </tr>
  </thead>
<tbody>
    <% @pages.each do |page| %>
      <% if page.published == false %>
      <tr>
        <td><%= page.slug %></td>
        <td><%= page.menu_label %></td>
        <td><%= page.published_at %></td>
        <td><%= page.published %>
        </td>
        <td><%= page.priority %></td>
        <td><%= page.title %></td>
        <td><%= page.description %></td>
        <td><%= page.h1 %></td>
        <td><%= page.content.html_safe %></td>
        <td><%= link_to raw('<i class="fa fa-sticky-note-o" aria-hidden="true"></i> Show'), page %></td>
        <td><%= link_to raw('<i class="fa fa-pencil-square-o" aria-hidden="true"></i> Edit'), edit_page_path(page) %></td>
        <td><%= link_to raw('<i class="fa fa-trash-o" aria-hidden="true"></i> Delete'), page, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
      <%end%>
    <% end %>
  </tbody>
  </table>
</div>
<%end%>

<h1> (<%= link_to raw('<i class="fa fa-plus" aria-hidden="true"></i> Add '), new_page_path %>)</h1> 
<table class="table table-bordered table-striped" style="font-size:12px;">
  <thead>
    <tr>
      <th>Slug</th>
      <th>Menu label</th>
      <th>Published at</th>
      <th>Published</th>
      <th>Priority</th>
      <th>Title</th>
      <th>Description</th>
      <th>H1</th>
      <th>Content(HTML TAGS OFF)</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pages.each do |page| %>
      <% if page.published == true %>
      <tr align="center">
        <td><a href="<%="http://"+request.host_with_port + "/pages/" + page.slug %>"><%= page.slug %></a></td>
        <td><%= page.menu_label %></td>
        <td><%= page.published_at %></td>
        <td><%= page.published %></td>
        <td><%= page.priority %></td>
        <td><%= page.title %></td>
        <td ><%= page.description %></td>
        <td><%= page.h1 %></td>
        <td><%= html_escape(page.content)%></td>
        <td><%= link_to raw('<i class="fa fa-sticky-note-o" aria-hidden="true"></i> Show'), page %></td>
        <td><%= link_to raw('<i class="fa fa-pencil-square-o" aria-hidden="true"></i> Edit'), edit_page_path(page) %></td>
        <td><%= link_to raw('<i class="fa fa-trash-o" aria-hidden="true"></i> Delete'), page, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
      <%end%>
    <% end %>
  </tbody>
</table>

app/views/pages/new.html.erb
<h1>New Page</h1>

<%= render 'form', page: @page %>

<%= link_to 'Back', pages_path %>

app/views/pages/show.html.erb
<br>
<h1>h1 tag: <%= @page.h1 %></h1>
<p></p>
<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Slug</th>
      <th>Menu label</th>
      <th>Published at</th>
      <th>Published</th>
      <th>Priority</th>
      <th>Title</th>
      <th>Description</th>
    </tr>
  </thead>

  <tbody>
<tr>
        <td><%= @page.slug %></td>
        <td><%= @page.menu_label %></td>
        <td><%= @page.published_at %></td>
        <td><%= @page.published %></td>
        <td><%= @page.priority %></td>
        <td><%= @page.title %></td>
        <td><%= @page.description %></td>
      </tr>
</tbody>
</table>

 <strong>Content:</strong>
 <div class="container">
  <%= raw(@page.content) %>
  </div>
<%= link_to raw('<i class="fa fa-trash-o" aria-hidden="true"></i> Delete'), @page, method: :delete, data: { confirm: 'Are you sure?' } %>
<%= link_to raw('<i class="fa fa-pencil-square-o" aria-hidden="true"></i> Edit'), edit_page_path(@page) %>   |  
<%= link_to raw('<i class="fa fa-level-up" aria-hidden="true"></i> Back'), pages_path %>